# config.yaml

prism_central:
  ip: "<Prism Central IP>"
  username: "<PC Username>"
  password: "<PC Password>" # Security Note: Consider pulling this from an Environment Variable instead!

job_settings:
  copy_type: "REFRESH"              # "REFRESH" or "BACKUP"
  source_env: "PRD"                 # Source Environment 
  target_env: "SUP"                 # Only needed if copy_type is REFRESH, if backup you can remove
  recovery_point_retention_days: 1  # The number of days to keep the Recovery Points 
  delete_vg_after_disconnect: True  # Set to True if old Volume Groups should be deleted

source:
  vm_name: "<Name of Source VM>"    # Source VM Name in Prism Central (Case Sensitive)
  host: "<IP of Source VM>"	        # Source VM IP address
  user: "<SSH Username>"            # SSH user with ssh keys configured for authentication
  freeze_command: "sudo /epic/PRD/bin/instfreeze"    # Command to freeze ODB
  thaw_command: "sudo /epic/PRD/bin/instthaw"        # Command to thaw ODB

target:
  vm_name: "<Name of Target VM>"    # Target VM Name in Prism Central (Case Sensitive)
  host: "<IP of Target VM>"         # Hostname or IP of Target VM
  user: "<SSH Username>"            # SSH user with ssh keys configured for authentication

vgs:                                # Define multipe VGs for mounting
  - ntnx_source_vg: "EPICVG"        # VG Name in Prism Central (Case Sensitive)
    source_lvm_vg: "EpicVG"         # VG Name as seen by LVM within the source
    target_lvm_vg: "EpicSUP"        # VG Name that you want LVM to use on target 
    mounts:
      lv_vol1: "/backup/vol1"       # LV Name for the filesystem on Source, Mountpoint on Target
      lv_vol2: "/backup/vol2"
      lv_vol3: "/backup/vol3"
      
  - ntnx_source_vg: "EPICvg2"
    source_lvm_vg: "EpicVG2"
    target_lvm_vg: "EpicSUP2"
    mounts:
      lv_vol4: "/backup/vol4"
      lv_vol5: "/backup/vol5"
